#!/bin/bash

indexLocation="~/.ferris/eaindex"
colspec=$1
if [ x$1 = x-P ]; then
    indexLocation=$2
    colspec=$3
    shift
    shift
fi
shift

if [ x$colspec = x ]; then
   echo ""
   echo "Usage $0 [ -P index-path ] colspec"
   echo ""
   echo "where colspec is like subtitles,col2,"
   exit 1
fi

echo "index  : $indexLocation"
echo "colspec: $colspec"
echo "$@"
export LIBFERRIS_UPDATE_COLUMN_LIST="$colspec"
feaindexadd --force -P $indexLocation "$@"


