#!/bin/bash

cat <<'HDR'
/******************************************************************************
*******************************************************************************
*******************************************************************************

    Copyright (C) 2001 YourNameHere

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.
  
    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.
  
    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the
    Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.

    For more details see the COPYING file in the root directory of this
    distribution.

    $Id: src-hh-LGPL,v 1.1 2005/07/04 08:53:02 ben Exp $

*******************************************************************************
*******************************************************************************
******************************************************************************/


HDR

cat <<REST
#ifndef _ALREADY_INCLUDED_${STARTOFNAME}_H_
#define _ALREADY_INCLUDED_${STARTOFNAME}_H_

    


#endif /* _ALREADY_INCLUDED_${STARTOFNAME}_H_ */
REST
