#!/bin/bash

# /******************************************************************************
# *******************************************************************************
# *******************************************************************************

#     libferris
#     Copyright (C) 2001 Ben Martin

#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.

#     You should have received a copy of the GNU General Public License
#     along with this program; if not, write to the Free Software
#     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#     For more details see the COPYING file in the root directory of this
#     distribution.

#     $Id: ferris-file-to-fifo,v 1.2 2006/08/13 11:43:12 ben Exp $

# *******************************************************************************
# *******************************************************************************
# ******************************************************************************/

#
# This exists mainly because I can't easily figure out how to tell bash that
# $(foo) has exited. If I run it and redirect its output then bash detects
# that the parent has exited and is OK. If run in $() notation bash waits
# for both parent and child to exit before running the enclosing command.
#

earl=$1;
if [ x$1 == "x--ea" ]; then
    attrselect="--ea $2"
    earl=$3;
fi

tmpfilename=/tmp/libferris-redirect-fifo-temp-$(id -u);
ferris-internal-file-to-fifo-command $attrselect -w $earl >|$tmpfilename;
cat $tmpfilename;
rm -f $tmpfilename;

