#!/bin/bash

CLIENT_APP_CFLAGS="-pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -I/usr/local/include -I/usr/local/include/FerrisLoki -I/usr/local/include/FerrisLoki/loki -I/usr/include/sigc++-2.0 -I/usr/lib64/sigc++-2.0/include   -pthread -I/usr/local/include/FerrisStreams -I/usr/include/sigc++-2.0 -I/usr/lib64/sigc++-2.0/include -I/usr/local/include -I/usr/local/include/FerrisLoki -I/usr/local/include/FerrisLoki/loki -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -I/usr/local/include -I/usr/local/include/FerrisLoki -I/usr/local/include/FerrisLoki/loki -I/usr/include/sigc++-2.0 -I/usr/lib64/sigc++-2.0/include        -I/usr/include/xalanc    -pthread -I/usr/include/gnome-vfs-2.0 -I/usr/lib64/gnome-vfs-2.0/include -I/usr/include/gconf/2 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gnome-vfs-module-2.0       -DQT_SHARED -I/usr/include/QtCore   -I/usr/include/Qt  -DQT_SHARED -I/usr/include/QtCore -I/usr/include/QtNetwork     -I/usr/include/kde4/   -DQT_SHARED -I/usr/include/QtCore   -I/usr/include/Qt           -pthread -I/usr/local/include/STLdb4 -I/usr/local/include -I/usr/local/include/FerrisLoki -I/usr/local/include/FerrisLoki/loki -I/usr/include/sigc++-2.0 -I/usr/lib64/sigc++-2.0/include -I/usr/local/include/FerrisStreams -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -I/usr/include/sigc++-2.0 -I/usr/lib64/sigc++-2.0/include   -I/usr/local/include/Ferris -DQT_SHARED -I/usr/include/QtCore"

CLIENT_APP_LIBS="-lfam -L/usr/local/lib64 -lfampp -lferrisloki -lsigc-2.0   -lcrypto -lssl  -lboost_wserialization -lboost_serialization -lboost_regex  -L/usr/local/lib64 -lferrisloki -lsigc-2.0   -Wl,--export-dynamic -pthread -L/usr/local/lib64 -lferrisstreams -lferrisloki -lsigc-2.0 -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lrt -lglib-2.0   -lxerces-c    -lxerces-c    -lxalan-c       -pthread -lgnomevfs-2 -lgconf-2 -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lrt -lglib-2.0         -lQtCore    -lQtNetwork -lQtCore       -L/usr/lib64/kde4/devel  -lkdeui -lkdecore    -lQtCore         -lssl -lcrypto     -lz   -lbz2  -Wl,--export-dynamic -pthread -L/usr/local/lib64 -lstldb4 -lpthread -lferrisstreams -lferrisloki -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lrt -lglib-2.0 -lsigc-2.0   -lsigc-2.0   -lsoprano -lQtCore   -lsopranoclient -lpopt -lferris -lgpgme "

g++ -g  -shared -fPIC kio_ferris.cpp  -o /tmp/DevelopBuild/ferris/exposures/kio/.libs/libkio_ferris.so.15.0.0 -L/usr/lib64/kde4/devel  -lkdeui -lkio -lkdecore  -I/usr/include/kde4 -lQtCore -lstdc++ $CLIENT_APP_CFLAGS $CLIENT_APP_LIBS -I/usr/include/gtk-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/gtk-2.0/include/ -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0

#g++ -g kio_ferris.cpp  -o /tmp/DevelopBuild/ferris/exposures/kio/.libs/libkio_ferris.so.15.0.0 -L/usr/lib64/kde4/devel  -lkdeui -lkio -lkdecore  -I/usr/include/kde4 -lQtCore -lstdc++ $CLIENT_APP_CFLAGS $CLIENT_APP_LIBS

cat /tmp/DevelopBuild/ferris/exposures/kio/.libs/libkio_ferris.so.15.0.0 >| /usr/lib64/kde4/libkio_ferris.so.15.0.0
